### ISSUE TITLE
Eternal loop in method Nichtterminal.absbuilder()

### ISSUE THREAD

**Issue by codemanyak** [BenjaminBak/EBNF-Check#1]
Interesting project. Mostly well done.
But if a closing parenthesis, bracket, or brace immediately follows to a non-terminal then method `Nichtterminal.Updatetoabs()` fails to detect it because it is still in status 1 and the non-ntcharlist check in status 1 misses to add the delimiting character to `raw`. In the event, the closing bracket etc. is missing in the `raw` list, such that method `Nichtterminal.absbuilder()` won't find it. As `depth` doesn't return to 0 therefore, `end` will never be set to `k` (clings to 0), an always empty `raw2` is passed to the recursive call, and after having reset `j` reset to 0, the same sequence is done again ad libitum.
This happens e.g. with the "TopLevelDomain" rule in the example grammar "txtfile.txt" in your project.

**Comment by BenjaminBak** [comment]
Oh thanks, for the comment. I will look into it. Originally I abandoned the project, because of other projects being more important, but I'm planning to pick it up again and finishing it. That particular issue wasn't apparent to me, but it good to know. The main function/point of the whole project is still missing though, the actual checking if a word belongs into a grammar or not. Currently, it is just a not properly working debugger for formal grammars. I'll try to get it finished in the next few days.

**Comment by codemanyak** [comment]
No problem. By the way, did you know about the [GOLD Parser](http://goldparser.org/index.htm) project? There is also a [Python engine](http://goldparser.org/engine/1/python/index.htm) for it. The GOLD parser does not process EBNF but only simple BNF, though. The GOLDBuilder is an excellent interactive tool (for Windows) to analyse and test grammars and it may produce very efficient parser code if one succeeds to formulate the grammar in a way that it allows a bottom-up analysis with only one symbol lookahead (LALR(1) property). Unfortunately, the project seems to have rested now for more than 8 years.
Of course its use would be too heavy for just an email address check (which could easily be done with a regular expression, of course, since the set of email addresses forms a regular language, i.e Chomsky type 3).

**Comment by BenjaminBak** [comment]
ok, that particular error should be fixed. I didn't know about the Gold Parser project, but I will look into it. The parsing part of the program is almost done by now, but it might give me some insides into parsing in general and how I could improve my current strategy of parsing the input-grammar. If it proves itself to be the better option without breaking the scope of the project too much I'll maybe switch to it and manage the recursions just as its own kind of object/nonterminal and unfold them later as much as needed, as I'm planning to do with my current method anyway.
